export const defaultVal = {
    personal_information: {
        name: {
            firstname: "",
            lastname: "",
            middlename: "",
            extension: "",
        },
        birth_date: "",
        birth_place: "",
        gender: "",
        citizenship: "",
        citizenship_dual_country: "",
        civil_status: "",
        civil_status_other: "",
        height: 0,
        weight: 0,
        blood_type: "",
        gsis_no: "",
        pagibig_no: "",
        philhealth_no: "",
        sss_no: "",
        tin_no: "",
        agency_employee_no: "",
        residential_address: {
            house_no: "",
            street: "",
            subdivision: "",
            barangay: "",
            city: "",
            province: "",
            zipcode: "",
        },
        residentail_permanent_is_same: false,
        permanent_address: {
            house_no: "",
            street: "",
            subdivision: "",
            barangay: "",
            city: "",
            province: "",
            zipcode: "",
        },
        telephone_no: "",
        mobile_no: "",
        email: "",
    },
    family_background: {
        spouse_name: {
            firstname: "",
            lastname: "",
            middlename: "",
            extension: "",
        },
        childrens: [
            {
                fullname: "",
                birth_date: "",
            },
        ],
        occupation: "",
        employer_business_name: "",
        business_address: "",
        telephone_no: "",
        fathers_name: {
            firstname: "",
            lastname: "",
            middlename: "",
            extension: "",
        },
        mothers_name: {
            firstname: "",
            lastname: "",
            middlename: "",
            maidenname: "",
        },
    },
    educational_background: {
        elementary: {
            school_name: "",
            degree: "",
            period_of_attendance: {
                from: "",
                to: "",
            },
            highest_unit: "",
            year_graduated: "",
            scholarship: "",
        },
        secondary: {
            school_name: "",
            degree: "",
            period_of_attendance: {
                from: "",
                to: "",
            },
            highest_unit: "",
            year_graduated: "",
            scholarship: "",
        },
        vocational: {
            school_name: "",
            degree: "",
            period_of_attendance: {
                from: "",
                to: "",
            },
            highest_unit: "",
            year_graduated: "",
            scholarship: "",
        },
        college: {
            school_name: "",
            degree: "",
            period_of_attendance: {
                from: "",
                to: "",
            },
            highest_unit: "",
            year_graduated: "",
            scholarship: "",
        },
        graduate_studies: {
            school_name: "",
            degree: "",
            period_of_attendance: {
                from: "",
                to: "",
            },
            highest_unit: "",
            year_graduated: "",
            scholarship: "",
        },
    },
    voluntary_works: [],
    learning_and_development: [],
    other_information: [],
};
